name: publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: set up gradle
        uses: gradle/gradle-build-action@v2

      - name: publish package
        run: ./gradlew publish
        env:
          access_token: ${{ secrets.access_token }}